// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cklnbaesxpvwmpurhxnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbG5iYWVzeHB2d21wdXJoeG5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MTA1MjIsImV4cCI6MjA2NjI4NjUyMn0.dJpDsQLl6TIdT1nL4qGlyHLXPyC70scjHrZK1eMZaaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);